apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: multi-domain-ingress
  namespace: myapp
spec:
  rules:
    - host: argocd.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: argocd-server
                port:
                  number: 80
    - host: onepiece-collector-dev.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: onepiece-collector
                port:
                  number: 8080
